language: php

php:
    - 7.1
    - 7.2
    - 7.3

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - travis_retry composer update --no-interaction --prefer-dist

script:
    - composer style-check
    - composer phpstan
    - composer test
